version: "3.8"

services:

  nginx:
    image: nginx:1.25
    ports:
      - "4001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    depends_on:
      - php
    networks:
      - backend
      - frontend
    restart: unless-stopped

  php:
    image: php:8.2-fpm
    volumes:
      - ./php:/var/www/html
    networks:
      - backend
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - mysql
    networks:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  backend:
  frontend:

